name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v4

      - name: Configurar CMake y compilar
        run: |
          rm -rf build # Asegura que la carpeta no exista antes de crearla
          mkdir build
          cd build
          cmake ..
          make

      - name: Ejecutar pruebas unitarias
        run: |
          cd build
          ctest --output-on-failure

      - name: Analizar código con SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=InternetService \
            -Dsonar.organization=tu-organizacion \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

      - name: Guardar artefactos de la compilación
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/

