name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Configurar CMake y compilar
        run: |
          rm -rf build  # Elimina el directorio si ya existe
          mkdir build
          cd build
          cmake ..
          make

      - name: Ejecutar pruebas unitarias
        run: |
          cd build
          ctest --output-on-failure

      - name: Configurar SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"  # Cambia esto si usas otro servidor
        run: |
          sonar-scanner \
            -Dsonar.projectKey=InternetService \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN

      - name: Publicar resultado de pruebas
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: build/Testing/Temporary/LastTest.log

